# Generated by Django 3.2.4 on 2021-08-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Childcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childcatname', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrencat', to='soannapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvname', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcountry', to='soannapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='soannapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsku', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=250)),
                ('pslag', models.SlugField(blank=True, max_length=200, null=True)),
                ('quantitystock', models.IntegerField()),
                ('purchaseprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sellprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discountprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weightunit', models.IntegerField()),
                ('productdetails', models.TextField(blank=True, max_length=500)),
                ('specification', models.TextField(blank=True, max_length=500)),
                ('unitorder', models.IntegerField(blank=True, null=True)),
                ('currentdt', models.DateField()),
                ('updatedt', models.DateField(blank=True, null=True)),
                ('liveproduct', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcategory', to='soannapp.category')),
                ('childcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pchildcategory', to='soannapp.childcategory')),
                ('productstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='soannapp.productstatus')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pquantity', to='soannapp.quantity')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psubcategory', to='soannapp.subcategory')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psupliers', to='soannapp.suppliers')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pweight', to='soannapp.weight')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('imageactive', models.SmallIntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgproduct', to='soannapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='childcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorychild', to='soannapp.subcategory'),
        ),
    ]
